### ISSUE TITLE
Enable 2-factor authentication on GitHub organization "arolgroup"

### ISSUE THREAD

**Issue by gmacario** [arolgroup/.github#2]
Enable 2FA at the organization level.

Prerequisite: All organization members must have 2FA enabled as well.
See https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa

**Comment by gmacario** [comment]
@arol-varesi as far as I can tell you are the only member in the organization "arolgroup" who has not yet enabled 2FA.

Please do it ASAP so that I can enable 2FA at the organization level

**Comment by arol-varesi** [comment]
Done

**Comment by gmacario** [comment]
OK, now that all people have 2FA enabled I can enable 2FA at the organization level as well.

**Comment by gmacario** [comment]
Done!

https://github.com/organizations/arolgroup/settings/security

![image](https://user-images.githubusercontent.com/75182/165339658-542db582-fb57-45d2-9fcc-455d4479dc1c.png)
